# Generated by Django 5.0 on 2023-12-15 11:06

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Home_1',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(blank=True, max_length=255)),
                ('sub_title', models.CharField(blank=True, max_length=255)),
                ('about', models.CharField(blank=True, help_text='Sarlavhaning pasti', max_length=255)),
                ('link', models.URLField(blank=True)),
                ('link_name', models.CharField(blank=True, max_length=255)),
                ('photo', models.ImageField(blank=True, upload_to='home_1/image')),
                ('low_title', models.CharField(blank=True, max_length=255)),
                ('photo_120', models.ImageField(blank=True, upload_to='home_1/low_images')),
                ('name', models.CharField(blank=True, help_text='Nomi rasmning ', max_length=255)),
                ('photo_432', models.ImageField(blank=True, upload_to='home_1/432_image')),
                ('about_432', models.CharField(blank=True, help_text='Rasm haqida', max_length=255)),
                ('price', models.DecimalField(decimal_places=3, max_digits=6)),
                ('logo', models.ImageField(blank=True, upload_to='home_1/logos_image')),
                ('date', models.DateTimeField(blank=True)),
            ],
            options={
                'verbose_name': 'Home_1',
                'verbose_name_plural': 'Homes_1',
            },
        ),
    ]
