# Generated by Django 5.0 on 2023-12-15 11:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home_1', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='home_1',
            name='date',
            field=models.DateField(blank=True),
        ),
    ]
