# Generated by Django 5.0 on 2023-12-22 16:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home_1', '0003_alter_home_1_photo'),
    ]

    operations = [
        migrations.CreateModel(
            name='Home_2',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('photo_370', models.ImageField(blank=True, upload_to='home_2/image')),
                ('name', models.CharField(blank=True, help_text='370 rasm nomi', max_length=255)),
                ('main_title', models.CharField(blank=True, max_length=255)),
                ('main_photo', models.ImageField(blank=True, upload_to='home_2/main_image')),
                ('main_sub_title', models.CharField(blank=True, max_length=255)),
                ('main_about', models.CharField(blank=True, max_length=255)),
                ('photo_432', models.ImageField(blank=True, upload_to='home_2/image_432')),
                ('about_432', models.CharField(blank=True, max_length=255)),
                ('old_price', models.DecimalField(decimal_places=4, max_digits=10)),
                ('price', models.DecimalField(decimal_places=4, max_digits=10)),
                ('photo_120', models.ImageField(blank=True, upload_to='home_2/image_120')),
                ('name_120', models.CharField(blank=True, max_length=255)),
                ('quantity', models.CharField(blank=True, max_length=255)),
                ('logo', models.ImageField(blank=True, upload_to='home_2/logo')),
                ('date', models.DateField(blank=True)),
                ('author', models.CharField(blank=True, max_length=255)),
                ('news_about', models.CharField(blank=True, max_length=255)),
            ],
            options={
                'verbose_name': 'Home_2',
                'verbose_name_plural': 'Homes_2',
            },
        ),
        migrations.AddField(
            model_name='home_1',
            name='photo_big',
            field=models.ImageField(blank=True, upload_to='home_1/big_image'),
        ),
    ]
