# Generated by Django 5.0 on 2023-12-16 10:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home_1', '0004_home_2'),
    ]

    operations = [
        migrations.AddField(
            model_name='home_2',
            name='main_photo',
            field=models.ImageField(blank=True, upload_to='home_2/main_image'),
        ),
    ]
