# Generated by Django 5.0 on 2023-12-19 10:38

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('home_1', '0005_home_2_main_photo'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Home_2',
        ),
    ]
