# Generated by Django 5.0 on 2023-12-16 15:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0002_full_with'),
    ]

    operations = [
        migrations.CreateModel(
            name='List_sidebar',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(blank=True, max_length=255)),
                ('sub_title', models.CharField(blank=True, max_length=255)),
            ],
            options={
                'verbose_name': 'List_sidebar',
                'verbose_name_plural': 'List_sidebars',
            },
        ),
    ]
