# Generated by Django 5.0 on 2023-12-20 15:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0009_my_account'),
    ]

    operations = [
        migrations.RenameField(
            model_name='cart',
            old_name='sub_title',
            new_name='photo_name',
        ),
        migrations.RenameField(
            model_name='compare',
            old_name='sub_title',
            new_name='photo_sub_title',
        ),
        migrations.RemoveField(
            model_name='full_with',
            name='sub_title',
        ),
        migrations.RemoveField(
            model_name='list_sidebar',
            name='sub_title',
        ),
        migrations.RemoveField(
            model_name='wishlist',
            name='sub_title',
        ),
        migrations.AddField(
            model_name='cart',
            name='photo',
            field=models.ImageField(blank=True, upload_to='Cart/images'),
        ),
        migrations.AddField(
            model_name='cart',
            name='photo_price',
            field=models.DecimalField(decimal_places=3, default=1, max_digits=6),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='compare',
            name='color',
            field=models.CharField(blank=True, max_length=50),
        ),
        migrations.AddField(
            model_name='compare',
            name='description',
            field=models.TextField(blank=True, max_length=255),
        ),
        migrations.AddField(
            model_name='compare',
            name='photo',
            field=models.ImageField(blank=True, upload_to='Compare/images'),
        ),
        migrations.AddField(
            model_name='compare',
            name='photo_title',
            field=models.CharField(blank=True, max_length=255),
        ),
        migrations.AddField(
            model_name='compare',
            name='price',
            field=models.DecimalField(decimal_places=3, default=1, max_digits=6),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='full_with',
            name='photo',
            field=models.ImageField(blank=True, upload_to='full_with/images'),
        ),
        migrations.AddField(
            model_name='full_with',
            name='photo_sub_title',
            field=models.CharField(blank=True, max_length=255),
        ),
        migrations.AddField(
            model_name='full_with',
            name='price',
            field=models.DecimalField(decimal_places=3, default=1, max_digits=6),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='grid_sidebar',
            name='photo',
            field=models.ImageField(blank=True, upload_to='grid_sidebar/images'),
        ),
        migrations.AddField(
            model_name='grid_sidebar',
            name='photo_sub_title',
            field=models.CharField(blank=True, max_length=255),
        ),
        migrations.AddField(
            model_name='grid_sidebar',
            name='price',
            field=models.DecimalField(decimal_places=3, default=1, max_digits=6),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='list_sidebar',
            name='photo',
            field=models.ImageField(blank=True, upload_to='List_sidebar/images'),
        ),
        migrations.AddField(
            model_name='list_sidebar',
            name='photo_sub_title',
            field=models.CharField(blank=True, max_length=255),
        ),
        migrations.AddField(
            model_name='list_sidebar',
            name='photo_title',
            field=models.CharField(blank=True, max_length=255),
        ),
        migrations.AddField(
            model_name='wishlist',
            name='photo',
            field=models.ImageField(blank=True, upload_to='Wishlist/images'),
        ),
        migrations.AddField(
            model_name='wishlist',
            name='photo_name',
            field=models.CharField(blank=True, max_length=255),
        ),
        migrations.AddField(
            model_name='wishlist',
            name='photo_price',
            field=models.DecimalField(decimal_places=3, default=1, max_digits=6),
            preserve_default=False,
        ),
    ]
