# Generated by Django 5.0 on 2023-12-21 11:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0010_rename_sub_title_cart_photo_name_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Product_detail',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('photo', models.ImageField(upload_to='product_detail/images')),
                ('title', models.CharField(blank=True, max_length=255)),
                ('sub_title', models.CharField(blank=True, max_length=255)),
                ('price', models.DecimalField(decimal_places=3, max_digits=6)),
                ('photo_123', models.ImageField(blank=True, upload_to='product_detail/photo_123')),
                ('text_title', models.CharField(blank=True, max_length=255)),
                ('text_sub_title', models.CharField(blank=True, max_length=255)),
                ('photo_432', models.ImageField(blank=True, upload_to='', verbose_name='product_detail/photo_432')),
                ('photo_sub_title', models.CharField(blank=True, max_length=255)),
                ('price_432', models.DecimalField(decimal_places=3, max_digits=6)),
            ],
            options={
                'verbose_name': 'Product_detail',
                'verbose_name_plural': 'Product_details',
            },
        ),
    ]
