# Generated by Django 5.0 on 2023-12-22 14:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0011_product_detail'),
    ]

    operations = [
        migrations.AddField(
            model_name='product_detail',
            name='photo_3',
            field=models.ImageField(blank=True, upload_to='product_detail/photo_3'),
        ),
        migrations.AlterField(
            model_name='product_detail',
            name='photo_432',
            field=models.ImageField(blank=True, upload_to='product_detail/photo_432'),
        ),
    ]
