# Generated by Django 5.0 on 2023-12-22 16:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0013_product_group'),
    ]

    operations = [
        migrations.CreateModel(
            name='Product_slider',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('photo', models.ImageField(blank=True, upload_to='product_slider/images')),
                ('title', models.CharField(blank=True, max_length=255)),
                ('sub_title', models.CharField(blank=True, max_length=255)),
                ('price', models.DecimalField(blank=True, decimal_places=3, max_digits=6)),
                ('photo_1', models.ImageField(blank=True, upload_to='product_slider/photo_1')),
                ('photo_sub_title', models.CharField(blank=True, max_length=255)),
                ('photo_2', models.ImageField(blank=True, upload_to='product_slider/photo_2')),
            ],
            options={
                'verbose_name': 'Product_slider',
                'verbose_name_plural': 'Product_sliders',
            },
        ),
        migrations.AlterModelOptions(
            name='product_group',
            options={'verbose_name': 'Product_group', 'verbose_name_plural': 'Product_groups'},
        ),
    ]
